version: '3'

services:
  php:
    build: ./docker/php
    command: php -S 0.0.0.0:8000 -t /public_html
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./public_html:/public_html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file: .env
    tty: true
    stdin_open: true

  db:
    build: ./docker/postgres
    command: postgres -c config_file="/etc/postgresql.conf"
    ports:
      - ${DBPORT}:${DBPORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql.conf
      - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      LC_ALL: C.UTF-8
      POSTGRESQL_USER: ${DBUSER}
      POSTGRESQL_PASS: ${DBPASS}
